sweep_config:
  method: random
metric:
  name: Train_loss
  goal: minimize
parameters:
    input_size:
        distribution: int_uniform
        min: 200
        max: 400
    seed:
        distribution: int_uniform
        min: 1
        max: 20
