sweep_config:
  method: bayes
metric:
  name: Train_F1
  goal: maximize
parameters:
    drop_out:
         distribution: uniform
         min: 0.1
         max: 0.3
    kernel_1:
        distribution: int_uniform
        min: 1
        max: 8
    kernel_2:
        distribution: int_uniform
        min: 1
        max: 8
    kernel_3:
        distribution: int_uniform
        min: 1
        max: 8
    kernel_4:
        distribution: int_uniform
        min: 1
        max: 8
    kernel_5:
        distribution: int_uniform
        min: 1
        max: 8
    kernel_6:
        distribution: int_uniform
        min: 1
        max: 8    
    dim_1:
        distribution: int_uniform
        min: 20
        max: 50
    dim_2:
        distribution: int_uniform
        min: 20
        max: 50
    nodes_1:
        distribution: int_uniform
        min: 60
        max: 120
    nodes_2:
        distribution: int_uniform
        min: 60
        max: 120
    input_size:
        distribution: int_uniform
        min: 350
        max: 500
