sweep_config:
    method: random
metric:
    name: Best_F1
    goal: maximize
parameters:
    beta1:
        distribution: uniform
        min: 0.89
        max: 0.99
    beta2:
        distribution: uniform
        min: 0.94
        max: 0.999
    learning_rate:
        distribution: uniform
        min: 0.000001
        max: 0.001