wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.34.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701435458.287845
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      - 83
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      - 83
      3:
      - 3
      - 13
      - 23
      - 24
      4: 3.10.13
      5: 0.16.0
      6: 4.34.1
      8:
      - 5
      13: linux-x86_64
