sweep_config:
  method: random
metric:
  name: Best_F1
  goal: maximize
parameters:
    # learning_rate:
    #     distribution: log_uniform
    #     min: 0.0001
    #     max: 0.1
    layer_scale:
         distribution: uniform
         min: 0.01
         max: 0.9
    stochastic_depth_prob:
         distribution: uniform
         min: 0.0001
         max: 0.001
    # input_size:
    #     distribution: int_uniform
    #     min: 250
    #     max: 500
    # l1_lambda:
    #     distribution: log_uniform
    #     min: 0.000001
    #     max: 0.0001

    kernel_1:
        distribution: int_uniform
        min: 1
        max: 7
    kernel_2:
        distribution: int_uniform
        min: 1
        max: 7
    kernel_3:
        distribution: int_uniform
        min: 1
        max: 7
    kernel_4:
        distribution: int_uniform
        min: 1
        max: 7
    kernel_5:
        distribution: int_uniform
        min: 1
        max: 7
    kernel_6:
        distribution: int_uniform
        min: 1
        max: 7    
    dim_2:
        distribution: int_uniform
        min: 14
        max: 60
    dim_3:
        distribution: int_uniform
        min: 14
        max: 60
    nodes_1:
        distribution: int_uniform
        min: 64
        max: 130
    nodes_2:
        distribution: int_uniform
        min: 64
        max: 130
