sweep_config:
  method: random
metric:
  name: Best_F1
  goal: maximize
parameters:
    input_size:
        distribution: uniform
        min: 270
        max: 330
    alpha:
        values: [1, 1.1, 1.2, 1.3, 1.4, 1.5]
    gamma:
        values: [1, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6]
    
      
      