sweep_config:
  method: random
metric:
  name: Best_F1
  goal: maximize
parameters:
    input_size:
        distribution: uniform
        min: 270
        max: 365
    alpha:
        values: [0.5, 1, 2, 3, 4]
    gamma:
        values: [0, 1, 2, 3, 4]
    
      
      