sweep_config:
    method: grid
metric:
    name: Val_loss
    goal: minimize
parameters:
    num_heads: 
        values: [2, 3 ,4 ,6 ,7 ,12 ,14 ,21 ,28]
    num_decoder_layers:
        values: [2, 3, 4, 5, 6]



