sweep_config:
    method: bayes
metric:
    name: Val_loss
    goal: minimize
parameters:
    beta1:
        distribution: uniform
        min: 0.88
        max: 0.99
    beta2:
        distribution: uniform
        min: 0.93
        max: 0.999
    learning_rate:
        distribution: uniform
        min: 1e-7
        max: 1e-3
    eps:
        distribution: uniform
        min: 1e-9
        max: 1e-7
    input_size:
        distribution: int_uniform
        min: 224
        max: 500
    ESS_alpha:
        values: [0.01, 0.1, 1, 4, 10, 100]
    MSE_alpha:
        values: [0.01, 0.1, 1, 4, 10, 100]




